version: "3"
services:
  python:
    build: ./docker/python
    volumes:
      - ./src:/src
      - ./data:/data
      - ./results:/results
    ports:
      - "5000:5000"
    networks:
      - default
networks:
  default:
    driver: bridge